### ISSUE TITLE
Missing src file in published build

### ISSUE THREAD

**Issue by Puddinglord** [dopecodez/pingman#2] opened 2020-05-20 21:01 UTC
I understand this is written with TypeScript and I tried going into the node module and building myself but then it says it can't find `tsconfig.json`. I am **not** using TypeScript in this project.

Is there a way to fix this?

**Comment by dopecodez** [comment] 2020-05-21 06:52
Thanks for raising the issue @Puddinglord . Looks like this was caused by a missing `files` field in package.json as per this issue [here](https://stackoverflow.com/questions/31642477/how-to-publish-a-npm-package-with-distribution-files). I just corrected the issue and published a new build in npm.

You don't need to build this for yourself as the typescript compiler builds everything into ES-compliant JavaScript straight out of the box. Just bump your `pingman` version to 1.0.4 , run `npm install` again and everything should be back to normal.

**Comment by dopecodez** [comment] 2020-05-23 07:11
Closing this - verified on windows 10 with pingman v1.0.4

**Closed by dopecodez** 2020-05-23 07:11 UTC
Labels: bug
